# Generated by Django 5.2.14 on 2026-05-31 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('interested_field', models.CharField(blank=True, max_length=255, null=True)),
                ('residence_country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('language_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'db_table': 'consultation_requests',
            },
        ),
    ]
